In [ ]:
x=int(input("Enter a value"))
print(x)

Enter a value56
56


In [ ]:
import numpy as np

In [ ]:
y=x+4

In [ ]:
y

60

In [ ]:
# Hello world

In [ ]:
'''multiple'''

'multiple'

In [ ]:
a='Bithi\'s code%'
a

"Bithi's code%"

In [ ]:
id(x)

10916256

In [ ]:
print(x,y)

56 60


In [ ]:
x,y,z=10,134,90

In [ ]:
z

90

In [ ]:
a=[3,4,5,6,7,8]

In [ ]:
a.append(9)

In [ ]:
a

[3, 4, 5, 6, 7, 8, 9]

In [ ]:
for x in a:
  print(x)

3
4
5
6
7
8
9


In [ ]:
sum=0
for x in a:
  sum=sum+x
print(sum)

42


In [ ]:
np.sum(a)

42

In [ ]:
sum=0
for x in range(1,10):
  if x%2==0:
    sum+=x

print(sum)

20


In [ ]:
n=int(input("Enter a number to check:\n"))
flag=1
for i in range(2,n):
  if n%2==0:
    flag=0
    break;

if flag:
  print('prime')
else:
  print('not prime')
  

Enter a number to check:
24
not prime


In [ ]:
for i in range(20,31):
  if i%2==0:
    continue
  print(i)

21
23
25
27
29


In [ ]:
for i in range(20,31):
  if i%2==0:
    pass
  else:
    print(i)

21
23
25
27
29


In [ ]:
def area(a,b):
  print(a*b)

In [ ]:
area(3,5)

15


In [ ]:
def area(a,b):
  return a*b

In [ ]:
c=area(5,6)

In [ ]:
c

30

In [ ]:
#fibnacci series

a=[]
n=int(input())
a.append(0)
a.append(1)
print(a[0],a[1])
for i in range(2,n):
  m=a[i-1]+a[i-2]
  a.append(m)
  print(a[i])

8
0 1
1
2
3
5
8
13


In [ ]:
#factorial
def fact(n):
  prod=1
  for i in range(1,n+1):
    prod=prod*i
  return prod
  #print(prod)


n=int(input())
f=fact(n)
print(n,f)

5
5 120


In [ ]:
a.pop()

In [ ]:
a.pop(4)

7

In [ ]:
sys.getsizeof(a)

144

In [ ]:
import sys

In [ ]:
if x<y:
  print('x<y')
elif x>y:
  print('x>y')
else:
  print('x==y')

x<y


In [ ]:
if x%2==0:
  print("Even")
else:
  print("Odd")

Even


In [ ]:
#max 
if x<y:
  if y>z:
    max=y
  else:
    max=z

else:
  if x>z:
    max=x
  else:
    max=z
print(max)


134


In [ ]:
def func(*n):
  sum=0
  for i in n:
    sum=sum+i
  return sum,i

s=func(4,7,2,4)
print(s)

(17, 4)


In [ ]:
#keyword argument
def func(m,*n,**l):
  print(l)


func(23,'bithi',67,[2,4],name='bithi',age=67)


{'name': 'bithi', 'age': 67}


In [ ]:
a=45
b=5

In [ ]:
#try catch

try:
  c=a/b
except Exception as e:
  print('Exception',e)
finally:
  print('resource closed!')
print(c)

resource closed!
9.0


In [ ]:
import math

In [ ]:
x=4

In [ ]:
print(math.pow(x,2))

16.0


In [ ]:
print(math.sqrt(x))

2.0


In [ ]:
print(math.pi)

3.141592653589793


In [ ]:
print(math.inf)

inf


In [ ]:
print(math.e)

2.718281828459045


In [ ]:
print(math.nan)

nan


In [ ]:
print(math.floor(45.7))

45


In [ ]:
print(math.ceil(45.2))

46


In [ ]:
print(math.factorial(x))

24


In [ ]:
print(math.sinh(30))

5343237290762.231


In [129]:
import numpy as np

In [131]:
a=np.array([[2,3,4,5],
         [3,5,6,7]])

In [132]:
a

array([[2, 3, 4, 5],
       [3, 5, 6, 7]])

In [133]:
a.ndim

2

In [134]:
a.size

8

In [135]:
a.shape

(2, 4)

In [136]:
a.flatten()

array([2, 3, 4, 5, 3, 5, 6, 7])

In [137]:
a.reshape(2,4)

array([[2, 3, 4, 5],
       [3, 5, 6, 7]])

In [138]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [139]:
b=np.array([[6,7],[8,9],[3,1]])
b

array([[6, 7],
       [8, 9],
       [3, 1]])

In [140]:
c=np.dot(a,b)
c

array([[31, 28],
       [82, 79]])

In [141]:
c=np.array([[2,3,4],[6,8,9]])
c

array([[2, 3, 4],
       [6, 8, 9]])

In [142]:
a+c

array([[ 3,  5,  7],
       [10, 13, 15]])

In [144]:
np.add(a,c)

array([[ 3,  5,  7],
       [10, 13, 15]])

In [145]:
np.subtract(c,a)

array([[1, 1, 1],
       [2, 3, 3]])

In [146]:
np.multiply(a,c)

array([[ 2,  6, 12],
       [24, 40, 54]])

In [147]:
np.dot(a,b)

array([[31, 28],
       [82, 79]])

In [148]:
def func(x,y=5):
  print(x**y)

func(2,4)
func(2)

16
32


In [150]:
#recursion

def fact(n):
  if n<=1:
    return 1
  else:
    return n*fact(n-1)

fact(4)

24

In [151]:
y=(lambda x:x**2)(5)
y

25

In [153]:
y=(lambda x,y,z:x*y*z)(3,5,2)
y

30

In [165]:
#zip unzip

x=['name','age','dept']
y=['Nasima',23,'CSE']
p=[2,4,5]

z=list(zip('123',x,y,p))
z


[('1', 'name', 'Nasima', 2), ('2', 'age', 23, 4), ('3', 'dept', 'CSE', 5)]

In [163]:
q=list(zip(*z))
q

[('1', '2', '3'), ('name', 'age', 'dept'), ('Nasima', 23, 'CSE'), (2, 4, 5)]