In [3]:
import numpy as np

In [333]:
arr=np.array([2,5,4,5])

In [334]:
arr

array([2, 5, 4, 5])

In [335]:
type(arr)

numpy.ndarray

In [336]:
arr.shape

(4,)

In [337]:
l1=[3,7,9,3,5]

In [338]:
l2=[7,9,0,2,4]

In [339]:
lst=np.array([l1,l2])

In [340]:
lst

array([[3, 7, 9, 3, 5],
       [7, 9, 0, 2, 4]])

In [341]:
lst.max()

9

In [342]:
lst.min()

0

In [343]:
lst.sum()

49

In [344]:
lst.max(axis=1)       #axis = 1 is row

array([9, 9])

In [345]:
lst.max(axis=0)      #axis = 0 is column

array([7, 9, 9, 3, 5])

In [346]:
lst.min(axis=1)

array([3, 0])

In [347]:
lst.min(axis=0)

array([3, 7, 0, 2, 4])

In [348]:
lst.shape

(2, 5)

In [349]:
lst.reshape(5,2)

array([[3, 7],
       [9, 3],
       [5, 7],
       [9, 0],
       [2, 4]])

In [350]:
lst

array([[3, 7, 9, 3, 5],
       [7, 9, 0, 2, 4]])

In [354]:
lst[0][4]

5

In [355]:
lst

array([[3, 7, 9, 3, 5],
       [7, 9, 0, 2, 4]])

In [357]:
lst.size   #total element

10

In [358]:
lst[:,:]

array([[3, 7, 9, 3, 5],
       [7, 9, 0, 2, 4]])

In [361]:
lst[:2,2:4]     #[row, column]

array([[9, 3],
       [0, 2]])

In [368]:
np.arange(0,10)   #0 to 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [379]:
arr=np.arange(0,20,step=2)

In [380]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [381]:
arr[:6]

array([ 0,  2,  4,  6,  8, 10])

In [382]:
arr*2

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [383]:
arr[3:]=500

In [384]:
arr

array([  0,   2,   4, 500, 500, 500, 500, 500, 500, 500])

In [385]:
arr<20

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [386]:
arr/10

array([ 0. ,  0.2,  0.4, 50. , 50. , 50. , 50. , 50. , 50. , 50. ])

In [388]:
arr[:]

array([  0,   2,   4, 500, 500, 500, 500, 500, 500, 500])

In [393]:
arr=arr.reshape(5,2)

In [395]:
arr

array([[  0,   2],
       [  4, 500],
       [500, 500],
       [500, 500],
       [500, 500]])

In [396]:
arr.sum(axis=0)

array([1504, 2002])

In [397]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [399]:
np.zeros(4,dtype=int)

array([0, 0, 0, 0])

In [400]:
np.ones((2,4),dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.random.rand(3,3)

array([[0.27872161, 0.34123291, 0.15933134],
       [0.12229217, 0.03929045, 0.64092506],
       [0.84433121, 0.53027781, 0.11279173]])

In [5]:
np.random.randn(4,4)

array([[-1.13054536,  0.46101541,  1.43237936, -1.14641859],
       [-0.03553314, -0.66302238,  2.48861059, -0.59844081],
       [-0.4274038 ,  0.11752399,  1.10979079, -0.95601293],
       [ 2.62051811,  0.13175432,  0.68548226,  1.03843092]])